### ISSUE TITLE
Possible to configure HSTS?

### ISSUE THREAD

**Issue by jarthod** [chrisDeFouRire/tlsproxy#3]
Currently the HSTS header returned contains `includeSubDomains` which can cause trouble is someone uses other subdomains of the one served by tlsproxy for non-ssl stuff. This should not be the default IMO, and the best would be an option to opt-in for the `includeSubDomains`.

**Comment by chrisDeFouRire** [comment]
TLSproxy doesn't set HSTS headers (because it's just a proxy and doesn't modify replies), so it must be your http server that's setting the headers

**Comment by jarthod** [comment]
Indeed, sorry about that!
