### ISSUE TITLE
GetCertificate debug: acme/autocert: no supported challenge type found

### ISSUE THREAD

**Issue by eugeneia** [chrisDeFouRire/tlsproxy#4]
I get the following error:

```
GetCertificate debug: acme/autocert: no supported challenge type found
```

What does it mean?

**Comment by chrisDeFouRire** [comment]
Hi! No later than this week, I've discovered that Lets Encrypt has changed something in their handling of the SNI challenge... A new acme/autocert version is available which makes use of HTTP challenge instead (which requires port 80...). I've had that problem on another project...

I'll try to take the time to fix tlsproxy... Were you actively using it? Are you just trying it? ie. is this an urgent matter for you?

**Comment by eugeneia** [comment]
No its not urgent. I ran into this while evaluating tlsproxy. No rush and thank you for the quick response! :-)

**Comment by chrisDeFouRire** [comment]
Fixed with alpn challenge
